### PR TITLE
use-observer memory leaks

### PR DESCRIPTION
**Pull request by alsotang**
every time we call useObserver, there is a new `new Reaction` created, but it doesn't dispose

### CODE REVIEW

**Comment by FredyC** [comment]
Nice catch! I am wondering if the test case can be made for this. It's implementation detail, but it would be nice to cover it somehow.

I am please fix linter issue (see travis).

**Comment by alsotang** [comment]
Yes, test should cover this. Which mock lib do you prefer? I always use this simple one: https://github.com/node-modules/mm

**Comment by alsotang** [comment]
I will add some code.
Change all `useRef(undefined)` to `useRef(null)`, because react official docs use the latter.

**Comment by FredyC** [comment]
> Yes, test should cover this. Which mock lib do you prefer? I always use this simple one: https://github.com/node-modules/mm

I am not sure how that module would help you write a test. Besides Jest already has a capability for [mocking modules](https://jestjs.io/docs/en/manual-mocks). Point is that test would somehow need to watch for creation and disposal of Reactions. It's pretty much implementation detail as I said. I am not sure on this one.

**Comment by alsotang** [comment]
I would take look at jest framework. I dont familiar with it now.

**Comment by alsotang** [comment]
I've write test cases for this pr and https://github.com/mobxjs/mobx-react-lite/pull/49

**Comment by alsotang** [comment]
@FredyC any response?

**Comment by FredyC** [comment]
LGTM. Thanks.

**Pull request merged**
