### PR TITLE
update react version in readme

### PR DESCRIPTION
**Pull request by barbalex**
16.7.0-alpha.2 instead of 16.7.0-alpha.0

### CODE REVIEW

**Comment by FredyC** [comment]
Right...Can you please update package.json as well? I am not sure, but I think these alpha versions wont get updated even when using `^`

**Comment by barbalex** [comment]
Done

**Comment by barbalex** [comment]
Seems that vscode does more than I realize...

Formatting corrected.

**Comment by FredyC** [comment]
And what about that Yarn? The `yarn.lock` should be updated :)

**Comment by barbalex** [comment]
I now did `yarn`, then `yarn update`. Hope that was correct.

**Comment by FredyC** [comment]
I guess it's fine, tests are passing so let's roll. Thanks :)

**Comment by barbalex** [comment]
Thanks so much for investing in this tool!

**Comment by FredyC** [comment]
Released in [v0.3.0](https://github.com/mobxjs/mobx-react-lite/releases/tag/v0.3.0)

**Pull request merged**
