### PR TITLE
check ci

### PR DESCRIPTION
**Pull request by pustovalov**

### CODE REVIEW

**Comment by FredyC** [comment]
Yea, it's not pick up at all, but it was working a month ago on PR #313. Something went wrong since then.

**Comment by pustovalov** [comment]
@FredyC can you add some commit into this PR?

**Comment by FredyC** [comment]
@pustovalov Seems you are right. No idea though how to change that, I don't see any permission settings or similar.

**Comment by pustovalov** [comment]
Looks like problem was in my forked repo, I didn't add public ssh key into my circle ci repo

**Pull request closed without merging**
