### PR TITLE
Use observable effect disposer test

### LINKED ISSUE #25: Possible memory leak in useObservableEffect
Probably not, but I just noticed in test coverage that the disposer is never called.

```ts
    useEffect(
        () => () => {
            if (disposerRef.current) {
                disposerRef.current()
            }
        },
        inputs
    )
```

I tried calling `unmount`, modify the store value again and render counters were the same so, in the essence, it seems to be working. However, the coverage hasn't changed with such test so it never gets called either way it seems.

In theory, it could be caused by the [asynchronous nature of `useEffect`](https://github.com/kentcdodds/react-testing-library/issues/215), but I tried switching it to `useLayoutEffect` which should be synchronous, but nothing has changed.

I am not really sure what might be wrong here and how to test it properly.

@xaviergonz

### PR DESCRIPTION
**Pull request by xaviergonz**
Closes #25

### CODE REVIEW

**Comment by FredyC** [comment]
Nope, coverage still reports that condition has never fired. Sadly, I don't have enough permissions to enable Coveralls for this repo, so I can only run it locally.

```
-------------------------|----------|----------|----------|----------|-------------------|
File                     |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-------------------------|----------|----------|----------|----------|-------------------|
All files                |    89.42 |    51.61 |    95.45 |    88.17 |                   |
 mobx-react              |      100 |      100 |      100 |      100 |                   |  
  jest.setup.js          |      100 |      100 |      100 |      100 |                   |
 mobx-react/src          |    89.32 |    51.61 |    95.45 |    88.04 |                   |
  ObserverComponent.ts   |    43.75 |    14.29 |       50 |    43.75 |... 35,36,41,42,44 |
  assertEnvironment.ts   |    66.67 |       50 |      100 |    66.67 |               5,8 |
  index.ts               |      100 |      100 |      100 |      100 |                   |
  observer.ts            |      100 |      100 |      100 |      100 |                   |
  staticRendering.ts     |      100 |      100 |      100 |      100 |                   |
  useComputed.ts         |      100 |      100 |      100 |      100 |                   |
  useObservable.ts       |      100 |      100 |      100 |      100 |                   |
  useObservableEffect.ts |      100 |    66.67 |      100 |      100 |                26 | <---
  useObserver.ts         |      100 |      100 |      100 |      100 |                   |
  utils.ts               |      100 |      100 |      100 |      100 |                   |
-------------------------|----------|----------|----------|----------|-------------------|
```

**Comment by xaviergonz** [comment]
well, if the disposer doesn't get called I don't see how the variable with the number of calls to the disposer turns into two
Maybe coveralls + react hooks don't get along well?

**Comment by FredyC** [comment]
> Maybe coveralls + react hooks don't get along well?

That's unlikely since all other files are just fine. I am not really sure what's wrong here.

**Comment by xaviergonz** [comment]
well, I just put a console log in line 26 and it shows twice...

**Comment by xaviergonz** [comment]
Using the code in this PR I mean

**Comment by xaviergonz** [comment]
maybe what coveralls means is that the if condition is never false since the disposer is always available?

**Comment by FredyC** [comment]
> maybe what coveralls means is that the if condition is never false since the disposer is always available?

Ah, that will be it :) So just for sake of coverage, there should be a test where it does not return a disposer and disable typescript check for that.

**Comment by xaviergonz** [comment]
hopefully that last push solves that

**Comment by FredyC** [comment]
Thanks, coverage is happy now :)

Btw, you have more permissions to enable https://coveralls.io/ for this repo?

**Comment by xaviergonz** [comment]
Nope :( I can just ask for it, but someone else has to approve it

**Pull request merged**
