### PR TITLE
Use circleci/node orb for CI

### PR DESCRIPTION
**Pull request by pustovalov**
https://circleci.com/developer/orbs/orb/circleci/node

### CODE REVIEW

**Comment by FredyC** [comment]
Odd, CircleCI doesn't show this PR at all so it's stuck here. I checked and `Build forked pull requests` is enabled. No idea what's wrong or how to force it.

**Comment by pustovalov** [comment]
should works now

**Comment by FredyC** [comment]
Interesting, wouldn't be expecting a problem on your side.

Just trying to figure out why coveralls are not reporting success. Then I will merge.

Thanks!

**Comment by FredyC** [comment]
Meh, no idea what's wrong, maybe someday later...

**Comment by pustovalov** [comment]
>Meh, no idea what's wrong, maybe someday later...

Usually people don't setup CI for forks, but I did this, to check my changes before creating PR.

Looks like it's using my CI account and show result from my build

My CI doesn't have `COVERALLS_REPO_TOKEN`:
https://app.circleci.com/pipelines/github/pustovalov/mobx-react-lite/7/workflows/df63289d-3668-441c-a0a0-e88510cefa75/jobs/31
```
Warning - Coveralls info could NOT be uploaded since the COVERALLS_REPO_TOKEN was not available
CircleCI received exit code 0
```

**Comment by FredyC** [comment]
I know, but `COVERALLS_REPO_TOKEN` is defined in CircleCI. It feels there is something wrong with that bash script which I don't understand.

image

**Comment by FredyC** [comment]
Looking at the Coveralls dashboard it receives data only from `master` branch builds, not from PRs, but I haven't found any settings there that would prevent it.

**Comment by pustovalov** [comment]
>I know, but COVERALLS_REPO_TOKEN is defined in CircleCI.

for https://app.circleci.com/pipelines/github/mobxjs/mobx-react-lite
yes

for https://app.circleci.com/pipelines/github/pustovalov/mobx-react-lite
no

**Comment by FredyC** [comment]
Right, I suppose it's this setting that is disabled now. Reading it for the first time I thought it's an opposite direction, but I suppose it should do the trick.

image

**Pull request merged**
